local settings = { noremap = true }
vim.api.nvim_set_keymap('n', '<leader>ga',       ':Git add --patch<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gb',       ':Gblame<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gc',       ':Gcommit<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gd',       ':Gdiff<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gf',       ':Gfetch<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gg',       ':Git<space>', settings)
vim.api.nvim_set_keymap('n', '<leader>gk',       ':Git checkout<space>', settings)
vim.api.nvim_set_keymap('n', '<leader>gl',       ':Gpull<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gp',       ':Gpush<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>gs',       ':Gstatus<cr><c-w><s-h>', settings)
vim.api.nvim_set_keymap('n', '<leader>gw',       ':Gwrite<cr>', settings)
vim.api.nvim_set_keymap('n', '<localleader>gc',  ':Gcommit --amend<cr>', settings)
vim.api.nvim_set_keymap('n', '<localleader>gw',  ':Git add --patch %<cr>', settings)
vim.api.nvim_set_keymap('n', '<leader>ge',       ':Gedit<space>', settings)
