 -- require('lualine').setup{
 --  options = {
 --    theme = 'tokyonight',
 --    section_separators = {'', ''},
 --    component_separators = {'', ''},
 --  },
 --  sections = {
 --    lualine_c = {
 --      {
 --        'diff',
 --        color_added = '#90ee91',
 --        color_modified = '#f0e12f',
 --        color_removed = '#ff0038',
 --        symbols = {added = ' ', modified = '柳 ', removed = ' '},
 --      },
 --      'filename',
 --    },
 --    lualine_x = {
 --      {
 --        'diagnostics',
 --        sources = {'nvim_lsp'},
 --        sections = {'error', 'warn', 'info'},
 --        color_error = '#ff0038', -- changes diagnostic's error foreground color
 --        color_warn = '#f0e12f', -- changes diagnostic's warn foreground color
 --        color_info = '#90ee91', -- Changes diagnostic's info foreground color
 --        symbols = {error = ' ', warn = ' ', info = ' '},
 --      },
 --      'encoding',
 --      'fileformat',
 --      'filetype',
 --    },
 --  },
-- }
